#!/usr/bin/env bash
# Bash script that:
# - Creates the file /var/run/myscript.pid containing its PID
# - Displays "To infinity and beyond" indefinitely
# - Displays "I hate the kill command" when receiving a SIGTERM signal
# - Displays "Y U no love me?!" when receiving a SIGINT signal
# - Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

PIDFILE="/var/run/myscript.pid"
echo $$ | sudo tee $PIDFILE >/dev/null



while :
do
    echo "To infinity and beyond"
    trap 'echo "I hate the kill command" && sudo rm $PIDFILE && kill -SIGKILL $$' SIGTERM
    trap 'echo "Y U no love me?!"&& exit' SIGINT
    sleep 2
done
