#!/usr/bin/env bash
# Bash (init) script 101-manage_my_process that manages manage_my_process

case "$1" in
    start)
        ./manage_my_process &
        echo $! > /var/run/my_process.pid
        echo "manage_my_process started"
        ;;
    stop)
        PID=$(cat /var/run/my_process.pid)
        kill $PID
        rm /var/run/my_process.pid
        echo "manage_my_process stopped"
        ;;
    restart)
        PID=$(cat /var/run/my_process.pid)
        kill $PID
        rm /var/run/my_process.pid
        ./manage_my_process &
        echo $! > /var/run/my_process.pid
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        exit 1
        ;;
esac

exit 0

