#!/usr/bin/env bash
# Bash script to print numbers from 1 to 100 with specific conditions:
# - If the number is divisible by both 3 and 5, print "FizzBuzz"
# - If the number is divisible by 3, print "Fizz"
# - If the number is divisible by 5, print "Buzz"
# - Otherwise, print the number itself

for ((i=1; i<=100; i++));
do
    if ((i % 3 == 0)) && ((i % 5 == 0));
    then
        echo "FizzBuzz"
    elif ((i % 3 == 0));
    then
        echo "Fizz"
    elif ((i % 5 == 0));
    then
        echo "Buzz"
    else
        echo "$i"
    fi
done

