#!/usr/bin/env bash
# Use awk to group visitors by IP and HTTP status code, count occurrences, sort, and format the output

awk '{print $1, $9}' apache-access.log | sort | uniq -c | sort -nr | awk '{print $1, $2, $3}'
