#!/usr/bin/env bash
# a Bash script that displays:

# -The content of the current directory
# -In a list format
# -Where only the part of the name after the first dash is displayed (refer to the example)

for file in *
do
    if [[ $file =~ ^[0-9]+-(.+)$ ]]; then
        echo "${BASH_REMATCH[1]}"
    fi
done
